language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change


php:
  - 5.4
  - 5.6
  - 7
  - hhvm

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
  allow_failures:
    - php: hhvm


before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

env:
  matrix:
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=0

  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/built-in-server-helper/
    - GH_REF: https://github.com/torounit/wp-built-in-server-helper.git
    - secure: "G6ugr3v6cOwWCh8sDsqn4NfJ74zO68n1xwDmPOjkhMr0jhnwdNcPgQzVA5WXf/8yV5I910UAm3XQrT5CajXgwt2Tcsli67Olu3R8Nqcwh0lqAK5Q4LdD5RoP2Ie2jY/ih4Z56CZEhiuZbG9Qp/YeN8j/kIEDf/y/VwzoX/s3OXI="
